# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8d3b48960d4a7dd7d206d20acc2bf2e3562a2ffd4af84f36b230b4c3e1f424631ee23739495c7a4c6bcdcb14429f9742d7c81ade43f4d04b9960922a6dccc08

test:
  secret_key_base: cccba4b86fd06aa9387aa4f67372e5aac1751d7cf57236ea81bc71dae652814262cf6d9f30791199dedaf85d4f58ef270940d1e0d1beb6f007dd17f80c2e0cfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
